2023-10-14 07:30:07,508 40 Internal Server Error: /posts/example/ /Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/utils/log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 33: 'get_available_languages', expected 'endcache'. Did you forget to register or load this tag?"), <traceback object at 0x7f8f892b95c0>)
Traceback (most recent call last):
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'get_available_languages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/NewsPaper/news/views.py", line 146, in get
    return HttpResponse(render(request, 'posts.html', context))
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/templatetags/cache.py", line 84, in do_cache
    nodelist = parser.parse(("endcache",))
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 33: 'get_available_languages', expected 'endcache'. Did you forget to register or load this tag?
2023-10-14 07:30:07,510 40 "GET /posts/example/ HTTP/1.1" 500 209042 /Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/servers/basehttp.py None
2023-10-14 07:30:10,101 40 Internal Server Error: /posts/example/ /Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/utils/log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 33: 'get_available_languages', expected 'endcache'. Did you forget to register or load this tag?"), <traceback object at 0x7f8f8934abc0>)
Traceback (most recent call last):
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'get_available_languages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/NewsPaper/news/views.py", line 146, in get
    return HttpResponse(render(request, 'posts.html', context))
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/templatetags/cache.py", line 84, in do_cache
    nodelist = parser.parse(("endcache",))
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 33: 'get_available_languages', expected 'endcache'. Did you forget to register or load this tag?
2023-10-14 07:30:10,102 40 "GET /posts/example/ HTTP/1.1" 500 209042 /Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/servers/basehttp.py None
2023-10-14 07:32:10,576 40 Internal Server Error: /posts/example/ /Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/utils/log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 11: 'trans', expected 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x7f8f89357580>)
Traceback (most recent call last):
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'trans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/NewsPaper/news/views.py", line 146, in get
    return HttpResponse(render(request, 'posts.html', context))
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 11: 'trans', expected 'endblock'. Did you forget to register or load this tag?
2023-10-14 07:32:10,577 40 "GET /posts/example/ HTTP/1.1" 500 226208 /Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/servers/basehttp.py None
2023-10-14 07:32:11,298 40 Internal Server Error: /posts/example/ /Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/utils/log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 11: 'trans', expected 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x7f8f892c5540>)
Traceback (most recent call last):
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'trans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/NewsPaper/news/views.py", line 146, in get
    return HttpResponse(render(request, 'posts.html', context))
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 11: 'trans', expected 'endblock'. Did you forget to register or load this tag?
2023-10-14 07:32:11,299 40 "GET /posts/example/ HTTP/1.1" 500 226208 /Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/servers/basehttp.py None
2023-10-14 07:32:13,202 40 Internal Server Error: /posts/example/ /Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/utils/log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 11: 'trans', expected 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x7f8f892d6080>)
Traceback (most recent call last):
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'trans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/NewsPaper/news/views.py", line 146, in get
    return HttpResponse(render(request, 'posts.html', context))
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 11: 'trans', expected 'endblock'. Did you forget to register or load this tag?
2023-10-14 07:32:13,203 40 "GET /posts/example/ HTTP/1.1" 500 226043 /Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/servers/basehttp.py None
2023-10-14 07:32:23,562 40 Internal Server Error: /posts/example/ /Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/utils/log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 11: 'trans', expected 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x7f8f892d5d00>)
Traceback (most recent call last):
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'trans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/NewsPaper/news/views.py", line 146, in get
    return HttpResponse(render(request, 'posts.html', context))
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 11: 'trans', expected 'endblock'. Did you forget to register or load this tag?
2023-10-14 07:32:23,563 40 "GET /posts/example/ HTTP/1.1" 500 225808 /Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/servers/basehttp.py None
2023-10-14 07:33:35,604 40 Internal Server Error: /posts/example/ /Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/utils/log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 11: 'trans', expected 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x7f8f8935ae40>)
Traceback (most recent call last):
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'trans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/NewsPaper/news/views.py", line 146, in get
    return HttpResponse(render(request, 'posts.html', context))
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 11: 'trans', expected 'endblock'. Did you forget to register or load this tag?
2023-10-14 07:33:35,606 40 "GET /posts/example/ HTTP/1.1" 500 225808 /Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/servers/basehttp.py None
2023-10-14 09:39:19,180 40 Internal Server Error: /accounts/signup/ /Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/utils/log.py (<class 'django.contrib.auth.models.Group.DoesNotExist'>, DoesNotExist('Group matching query does not exist.'), <traceback object at 0x7f96381e3480>)
Traceback (most recent call last):
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/allauth/decorators.py", line 20, in wrap
    resp = function(request, *args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/allauth/account/views.py", line 234, in dispatch
    return super(SignupView, self).dispatch(request, *args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/allauth/account/views.py", line 77, in dispatch
    response = super(RedirectAuthenticatedUserMixin, self).dispatch(
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/allauth/account/views.py", line 207, in dispatch
    return super(CloseableSignupMixin, self).dispatch(request, *args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/allauth/account/views.py", line 105, in post
    response = self.form_valid(form)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/allauth/account/views.py", line 248, in form_valid
    self.user = form.save(self.request)
  File "/Users/alena/PycharmProjects/NewsPortal/NewsPaper/news/forms.py", line 37, in save
    common_group = Group.objects.get(name='common')
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.Group.DoesNotExist: Group matching query does not exist.
2023-10-14 09:39:19,184 40 "POST /accounts/signup/ HTTP/1.1" 500 125087 /Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/servers/basehttp.py None
2023-10-14 09:52:02,261 40 Internal Server Error: /posts/upgrade/ /Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/utils/log.py (<class 'django.contrib.auth.models.Group.DoesNotExist'>, DoesNotExist('Group matching query does not exist.'), <traceback object at 0x7f7ae851dcc0>)
Traceback (most recent call last):
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/NewsPaper/news/views.py", line 123, in became_author
    authors_group = Group.objects.get(name='authors')
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.Group.DoesNotExist: Group matching query does not exist.
2023-10-14 09:52:02,263 40 "GET /posts/upgrade/ HTTP/1.1" 500 78857 /Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/servers/basehttp.py None
2023-10-14 09:52:09,781 40 Internal Server Error: /posts/upgrade/ /Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/utils/log.py (<class 'django.db.utils.IntegrityError'>, IntegrityError('duplicate key value violates unique constraint "news_author_user_id_key"\nDETAIL:  Key (user_id)=(1) already exists.\n'), <traceback object at 0x7f7ad9cc5d80>)
Traceback (most recent call last):
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "news_author_user_id_key"
DETAIL:  Key (user_id)=(1) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/NewsPaper/news/views.py", line 122, in became_author
    Author.objects.create(user=user)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1820, in execute_sql
    cursor.execute(sql, params)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "news_author_user_id_key"
DETAIL:  Key (user_id)=(1) already exists.

2023-10-14 09:52:09,782 40 "GET /posts/upgrade/ HTTP/1.1" 500 148187 /Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/servers/basehttp.py None
2023-10-14 09:52:20,816 40 Internal Server Error: /posts/upgrade/ /Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/utils/log.py (<class 'django.db.utils.IntegrityError'>, IntegrityError('duplicate key value violates unique constraint "news_author_user_id_key"\nDETAIL:  Key (user_id)=(1) already exists.\n'), <traceback object at 0x7f7ad9cdd540>)
Traceback (most recent call last):
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "news_author_user_id_key"
DETAIL:  Key (user_id)=(1) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/NewsPaper/news/views.py", line 122, in became_author
    Author.objects.create(user=user)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1820, in execute_sql
    cursor.execute(sql, params)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "news_author_user_id_key"
DETAIL:  Key (user_id)=(1) already exists.

2023-10-14 09:52:20,817 40 "GET /posts/upgrade/ HTTP/1.1" 500 148187 /Users/alena/PycharmProjects/NewsPortal/venv/lib/python3.8/site-packages/django/core/servers/basehttp.py None
